### PR TITLE
Fix MIDI Continue from sequencer start

### PR DESCRIPTION
**Pull request by ggVGc**
Closes https://github.com/datomusic/duo-imxrt/issues/152

Resets the sequencer clock when starting, rather than keeping a running clock and waiting for the next step alignment.

### CODE REVIEW

**Comment by ggVGc** [comment]
@DavidMenting This should fix the issue, and is ready to merge unless you find any additional issues.

**Comment by DavidMenting** [comment]
Seems to work nicely. I don't prefer the single line functions, though, so leaving the last force push out should keep things more consistent with the rest of the codebase.

**Comment by ggVGc** [comment]
@DavidMenting It's an unrelated formatting change for this PR, which is why I reverted it.
I can apply it to `main` instead to keep this PR cleaner.

**Comment by ggVGc** [comment]
Done in https://github.com/datomusic/duo-imxrt/commit/2f9b704b70a9fcfb60f9142e61a64a8a5a2223bf

**Comment by ggVGc** [comment]
@DavidMenting with the latest commit, the play button fades out when the sequencer is stopped. I think this is nicer than the previous (random) behaviour, but I'm not sure if you would prefer it to instead turn off completely when stopping and then start fading in? It's just a matter of adding an offset of 12 ot the fade value in `Leds.h` in that case.
If you think this current behaviour is good, I think we can merge this?

**Comment by ggVGc** [comment]
After playing with it some more, I'm not sure if this behaviour is better than going to button off directly.
This fade-out looks nice, but also makes it feel like the button didn't do anything...
Setting `clock = 12` in `Sequencer::stop()` gives the more immediate behaviour.

**Comment by DavidMenting** [comment]
I agree with your findings. Let's set them to 12. We'll conduct some more testing on this branch before merging.

**Comment by ggVGc** [comment]
@DavidMenting latest commit should have the behaviour we want, I think.

**Pull request merged**
