### PR TITLE
Unify repositories, Step 1

### PR DESCRIPTION
**Pull request by ggVGc**
First steps to making a unified repository for the Duo firmware again, containing all platforms and configurations.
Currently, very simple steps have been taken.
- Moved everything relating to the imxrt1010 build into `platform/imxrt1010`. This still builds as usual from this directory.
- Copied everything necessary to build the `brains1` firmware into `platform/brains1`. Building from here also works, using the old Makefile.
- Both builds are currently isolated and are not sharing any firmware code (yet).
- The `Audio` library was a submodule in the original `duo-firmware` repo, however the commit it points to no longer exists in `datomusic/Audio`, and the commit it references is 7 years old. Hence I just copied this Audio dir in the current state rather than it being a submodule. We could revisit this, however the `brains1` build could be considered "locked" in relation to dependencies like this, I think?

Next steps:
- [ ] Gradually make repositories share firmware code, while introducing necessary abstractions along the way. (probably in branch based off of this one, to keep things cleaner)
- [ ] Look into what changes might be useful to make building different platforms / configurations better. Currently different hardware configurations are only relevant for `imxrt1010`, I believe.

### CODE REVIEW

**Comment by DavidMenting** [comment]
All right, this is a nice start. I think it's a good idea to freeze the original duo-firmware as much as possible seeing that we probably won't be developing for the K20 platform any further.

My proposal would be to look at the tinyUF2 / circuitpython directory structure and base ours loosely on that:

root
- platforms
- - imxrt
- - - boards
- - - - imxrt1010_evk
- - - - brains2_beta
- - - - brains2
- - k20
- - - boards
- - - - brains1

**Comment by ggVGc** [comment]
@DavidMenting This is now in a state where I think we could merge it as a first step in unification.
Most of the `duo-firmware` files are shared, and the ones that aren't are the ones with the most differences as well as least value for sharing initially (I think), Mainly it's the Synth, DrumSynth and Leds files that I believe we won't necessarily edit that much in the near future, and until then we might still get good value from the current shared stuff.

There's also stuff in the old `src.ino` that can be more unified, such as the handling of keys. I believe we can modify that when/if we edit that functionality though, and it's fairly easily testable changes when we do that.

The potential reorganization of the platform stuff can also be done separately I think, and is not something that will impact functionality (if it still builds after reorganization it should be fine).

So, I suggest we test this PR in the current state on all versions of the Duo and see if anything is broken, and if it's okay, we can merge this and start doing edits in the shared part of the code as we wish. I have already done some quick tests, and on my devices things seem good so far.

**Comment by ggVGc** [comment]
@DavidMenting This is now in a state where I think we could merge it as a first step in unification.
Most of the `duo-firmware` files are shared, and the ones that aren't are the ones with the most differences as well as least value for sharing initially (I think), Mainly it's the Synth, DrumSynth and Leds files that I believe we won't necessarily edit that much in the near future, and until then we might still get good value from the current shared stuff.

There's also stuff in the old `src.ino` that can be more unified, such as the handling of keys. I believe we can modify that when/if we edit that functionality though, and it's fairly easily testable changes when we do that.

The potential reorganization of the platform stuff can also be done separately I think, and is not something that will impact functionality (if it still builds after reorganization it should be fine).

So, I suggest we test this PR in the current state on all versions of the Duo and see if anything is broken, and if it's okay, we can merge this and start doing edits in the shared part of the code as we wish. I have already done some quick tests, and on my devices things seem good so far.

**Comment by ggVGc** [comment]
The best way to check code changes is to check each sub-PR that I merged into this one.

**Comment by DavidMenting** [comment]
Currently this builds perfectly fine for both platforms on my machine. The [LED flicker issue](https://github.com/datomusic/duo-imxrt/issues/49) exhibits itself in builds for imxrt1010 builds.

Platforms are now named 'brains1' and 'imxrt1010'. I suggest we pick one of those names as the basis for distinguishing platforms. Seeing that the iMX RT naming is a mess (is it imxrt or mimxrt? is it RT1010 or RT1011?) I think 'brains1' and 'brains2' would work better than what we have now, so let's rename 'imxrt1010' to 'brains2'.

**Comment by DavidMenting** [comment]
Two issues have popped up in this branch:
https://github.com/datomusic/duo-imxrt/issues/98
https://github.com/datomusic/duo-imxrt/issues/99

**Pull request merged**
